services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  App\EventListener\JsonRpcContentTypeRemover:
    tags:
    - { name: kernel.event_listener, event: kernel.response, priority: -100 }

  App\EventListener\ExceptionToErrorConverter:
    arguments:
    - '@serializer'
    tags:
    - { name: kernel.event_listener, event: kernel.exception, priority: 200 }

  App\EventListener\ExceptionToInternalServerErrorConverter:
    arguments:
    - '@logger'
    - '@serializer'
    tags:
    - { name: kernel.event_listener, event: kernel.exception, priority: 100 }
